In [1]:
import pandas as pd
import numpy as np
import nltk

In [4]:
df = pd.read_csv("dataframe_containing_job_descriptions.csv",index_col='Unnamed: 0')
df.head()

,Main Job Title,Searched Job Title,Company Name,skills,description,location,responsibilty/activity,education,Experience,Certifications,salary,links,name,exp,job
0,Application Developer,Application Developer,IBM India Pvt. Limited,IT-Skills Java CSS Javascript SAP Blackberry A...,None,Bengaluru/Bangalore,None,None,6-8 Yrs,,Not disclosed,https://www.naukri.com/job-listings-applicatio...,None,None,None
1,Application Developer,Application Developer,IBM India Pvt. Limited,Performance-tuning GIT Integration-testing Agi...,None,Bangalore/Bengaluru,None,None,2-5 Yrs,,Not disclosed,https://www.naukri.com/job-listings-applicatio...,None,None,None
2,Senior Application Developer,Application Developer,SHURE AUDIO TECHNOLOGIES PRIVATE LIMITED,Angularjs Web-Technologies Javascript Bootstra...,OverviewResponsible for providing technical ex...,Hyderabad/Secunderabad,responsible for integrating our Enterprise App...,"Education\nUG :B.Sc in Computers, B.Tech/B.E. ...",5-8 Yrs,,Not disclosed,https://www.naukri.com/job-listings-senior-app...,None,None,None
3,Senior Application Developer,Application Developer,ARETHOS,.Net-Core Microsoft-Azure ASP.Net-MVC program-...,"Roles and ResponsibilitiesDesign, code, test, ...","Singapore, Chandigarh",None,"Education\nUG :BCA in Any Specialization, B.Sc...",4-9 Yrs,,"5,00,000 - 12,00,000 PA.",https://www.naukri.com/job-listings-senior-app...,None,None,None
4,Web Application Developer,Application Developer,GENPACT India Private Limited,C# CSS LINQ Telerik-Controls ASP.Net-Ajax Java...,None,Bangalore/Bengaluru,None,None,3-6 Yrs,,Not disclosed,https://www.naukri.com/job-listings-net-web-ap...,None,None,None

In [5]:
jobs = pd.read_excel("/Work/files/Semantic Titles.xlsx",sheet_name='Sheet1')
jobs.head(2)

,Job Title,Semantic Words,C,D,E,F,G,H,I,J,...,Q,R,S,T,U,V,W,X,Y,Z
0,Application Developer,Application Developer,Senior Application Developer,Web Application Developer,Mobile Application Developer,Lead Application Developer,Sap Advanced Business Application Programming ...,Senior Web Application Developer,Advanced Business Application Developer,System Application Developer,...,Application Support Developer,Junior Application Developer,Principal Application Developer,Senior Advanced Business Application Programmi...,Internet Application Developer,Senior Oracle Application Developer,Senior Sap Advanced Business Application Progr...,Application Developer Contract,Network Application Developer,NaN
1,Application Engineer,Application Engineer,Senior Application Engineer,Field Application Engineer,Application Support Engineer,Sales Application Engineer,Application System Engineer,Application Specific Integrated Circuit Design...,Application Specific Integrated Circuit Engineer,Product Application Engineer,...,Lead Application Engineer,Project Application Engineer,Application Engineering Manager,Service Application Engineer,Web Application Engineer,Senior Application Specific Integrated Circuit...,Senior Application Support Engineer,Staff Application Engineer,Senior Application Specific Integrated Circuit...,Customer Application Engineer

## MAIN FUNCTION

In [16]:
def skillarray(X,job):
    x = X[X['Searched Job Title']==job]
    if(len(x)==0):
        return np.array(['None','None','None','None','None'])
    alllist = []
    findict = {}
    for i in x['skills']:
        for j in i.split():
            try:
                findict[j.lower()]+=1
            except:
                findict[j.lower()] = 0
            alllist.append(j.lower())
    alllist = list(np.unique(np.array(alllist)))
    skillset = pd.DataFrame([findict]).transpose()
    skillset.reset_index(inplace=True)
    skillset.columns = ['skills','counts']
    skillset.sort_values('counts',ascending=False,inplace=True)
    skillset['percentage'] = (skillset['counts']/len(x))*100
    skillset['percentage'] = skillset['percentage'].astype(int)
    skillset['fin'] = skillset['skills']+" ("+skillset['percentage'].astype(str)+"%)"
    return np.array(skillset['fin'][0:5])

## MAKING THE DATAFRAME

In [17]:
skilldict = {}
for i in jobs['Job Title']:
    skilldict[i] = skillarray(df,i)

## final dataframe

In [18]:
pd.DataFrame(skilldict).transpose()

,0,1,2,3,4
Application Developer,it-skills (27%),business-process (14%),javascript (12%),oracle (12%),communication (12%)
Application Engineer,linux (12%),jenkins (10%),java (10%),configuration-management (8%),git (8%)
Application Sales Specialist,sales (40%),application-development (16%),it-skills (13%),lead-generation (13%),digital-marketing (10%)
Area Manager,sales (14%),marketing (12%),area-management (12%),business-development (10%),area-sales-manager (8%)
Area Sales Manager,area-sales (33%),business-development (27%),area-sales-management (22%),sales (20%),channel-sales (20%)
...,...,...,...,...,...
Web Manager,web-technologies (20%),it-skills (20%),project-management (12%),seo (10%),javascript (10%)
Web Programmer,php (29%),javascript (22%),html (22%),web-technologies (20%),mysql (20%)
Web Specialist,it-skills (22%),web-technologies (15%),social-media (11%),none (11%),javascript (8%)
Web User Interface Developer,web-ui (35%),javascript (33%),css (18%),html (16%),angular (11%)
Webmaster,html (42%),google-analytics (26%),javascript (22%),css (20%),seo (20%)